from fastapi import (
    APIRouter,
    HTTPException,
)

from app.core.network_guard import (
    get_network_telemetry,
    read_recent_audit_entries,
    verify_sovereignty,
)

from app.services.progress import (
    progress_manager,
)


router = APIRouter()


# ============================================================
# NETWORK TELEMETRY
# ============================================================

@router.get("/network-audit")
def get_network_audit(
    limit: int = 100,
):
    """
    Return real network telemetry generated by the
    socket-level air-gap guard.
    """

    limit = max(
        1,
        min(limit, 1000),
    )

    telemetry = (
        get_network_telemetry(
            limit=max(
                limit,
                100,
            )
        )
    )

    return {
        "success": True,
        "telemetry": telemetry,
        "entries":
            read_recent_audit_entries(
                limit
            ),
    }


# ============================================================
# SOVEREIGNTY VERIFICATION
# ============================================================

@router.get("/sovereignty")
def sovereignty_verification():
    """
    Run deterministic local sovereignty checks.

    No public endpoint is contacted.
    """

    try:

        return verify_sovereignty()

    except Exception as exc:

        raise HTTPException(
            status_code=500,
            detail=(
                "Sovereignty verification "
                f"failed: {exc}"
            ),
        )


@router.get("/sovereignty/verify")
def sovereignty_verify():

    return sovereignty_verification()


# ============================================================
# AGENT AUDIT TIMELINE
# ============================================================

@router.get(
    "/agent-audit/{session_id}"
)
def agent_audit(
    session_id: str,
):

    return {
        "session_id":
            session_id,

        "events":
            progress_manager.get_history(
                session_id
            ),
    }